// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Footer() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<footer class=\"site-footer\"><div class=\"container footer-grid\"><div class=\"footer-intro\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Brand().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<p>Tecnologia para pesquisa cadastral, identidade, prevenção de fraudes e gestão logística no transporte.</p></div><div><h2>Soluções</h2><a href=\"/solucoes/pesquisa-cadastral-de-motoristas\">Cargo Score</a> <a href=\"/solucoes/biometria-facial\">Biometria facial</a> <a href=\"/solucoes/gestao-logistica\">Cargo Truck</a> <a href=\"/integracoes/api\">Integrações via API</a></div><div><h2>Viagate</h2><a href=\"/sobre\">Sobre</a> <a href=\"/blog\">Conteúdos</a> <a href=\"/contato\">Contato</a> <a href=\"/llms.txt\">llms.txt</a></div><div><h2>Contato</h2><a href=\"mailto:contato@viagate.com.br\">contato@viagate.com.br</a> <a href=\"tel:+5541999623600\">+55 41 99962-3600</a><p>Curitiba, Paraná, Brasil</p></div></div><div class=\"container footer-bottom\"><p>© 2026 Viagate Tecnologia.</p><div><a href=\"/termos-uso-politica-privacidade#politica-de-privacidade\">Privacidade</a><a href=\"/termos-uso-politica-privacidade#termos-de-uso\">Termos</a></div></div></footer>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
