package content

import "github.com/viagate/site/internal/site"

var analyses = []site.AnalysisReference{
	{
		Slug:            "biometria-facial-prova-de-vida",
		Category:        "Identidade",
		Subject:         "Pessoa",
		Name:            "Biometria facial e prova de vida",
		Icon:            "scan-face",
		Title:           "Biometria facial e prova de vida: o que é e como funciona no transporte",
		MetaDescription: "Entenda o que são biometria facial e prova de vida, como entram na validação de motoristas e quais cuidados devem acompanhar o uso dessa análise.",
		Lead:            "Biometria facial e prova de vida ajudam a confirmar identidade e presença em uma jornada digital antes de cadastros, análises ou etapas sensíveis da operação.",
		Definition:      "Biometria facial é uma forma de comparar características do rosto com uma referência associada à identidade apresentada. A prova de vida acrescenta uma verificação de presença no momento da jornada, ajudando a diferenciar uma pessoa presente de uma simples imagem estática ou reprodução.",
		Purpose:         "No transporte, a combinação pode ser usada para vincular o motorista ou usuário ao processo que está sendo executado e registrar uma evidência de identidade antes que outras consultas ou decisões avancem.",
		Scope: []string{
			"Captura facial realizada pelo navegador de um dispositivo compatível.",
			"Prova de vida para verificar presença durante a jornada de validação.",
			"Associação do status biométrico ao cadastro ou processo que originou a solicitação.",
			"Registro de contexto do acesso, como localização ou dispositivo, quando aplicável ao fluxo e autorizado.",
		},
		Process: []string{
			"A empresa inicia a validação pelo sistema ou por uma integração.",
			"A pessoa recebe um link e segue as orientações de captura pelo navegador.",
			"A biometria e a prova de vida são processadas dentro da jornada configurada.",
			"O status retorna ao processo de origem para ser combinado com os demais critérios da operação.",
		},
		Interpretation: "O resultado biométrico é uma evidência de identidade e presença dentro de um processo. Ele não deve ser interpretado isoladamente como aprovação cadastral, autorização de pagamento ou conclusão definitiva sobre risco.",
		Limitations: []string{
			"Dados biométricos vinculados a uma pessoa são dados pessoais sensíveis e exigem finalidade, base legal, segurança, acesso e retenção compatíveis com a LGPD.",
			"Qualidade da câmera, iluminação, conectividade e compatibilidade do dispositivo podem afetar a jornada.",
			"Biometria reduz incerteza de identidade, mas não elimina sozinha fraude ou outros riscos operacionais.",
		},
		RelatedSolutionName: "Biometria facial Viagate",
		RelatedSolutionPath: "/solucoes/biometria-facial",
		FrequentlyAsked: []site.FAQ{
			{Question: "Prova de vida e biometria facial são a mesma coisa?", Answer: "Não. A biometria compara características faciais associadas à identidade, enquanto a prova de vida verifica a presença da pessoa durante a jornada. As duas verificações podem ser usadas em conjunto."},
			{Question: "É necessário instalar aplicativo?", Answer: "Na solução Viagate, a jornada pode ser realizada pelo navegador de um smartphone ou computador com câmera compatível."},
			{Question: "A biometria sozinha aprova um motorista?", Answer: "Não. O status biométrico é uma evidência de identidade e pode ser combinado com documentos, registros e critérios definidos pela operação."},
		},
	},
	{
		Slug:            "dados-cadastrais",
		Category:        "Identidade",
		Subject:         "Pessoa",
		Name:            "Dados cadastrais",
		Icon:            "user-check",
		Title:           "Dados cadastrais de motoristas: o que são e como entram na análise",
		MetaDescription: "Veja como dados cadastrais de motoristas são organizados, comparados e usados como base para consultas, validações e decisões operacionais.",
		Lead:            "Dados cadastrais formam a base de identificação do processo e permitem relacionar a pessoa informada aos documentos, consultas e validações usados pela operação.",
		Definition:      "Dados cadastrais são informações de identificação e cadastro associadas a uma pessoa dentro de um processo. No contexto de transporte, eles servem como referência para organizar a pesquisa de um motorista e relacionar documentos, registros, biometria e demais evidências ao mesmo cadastro.",
		Purpose:         "Uma base cadastral consistente reduz consultas desconectadas e facilita a comparação entre o que foi informado pela operação e o que retorna das fontes ou validações contratadas.",
		Scope: []string{
			"Informações de identificação fornecidas no cadastro da pessoa.",
			"Dados retornados por fontes cadastrais disponíveis no projeto contratado.",
			"Comparação entre cadastro, documentos e outras validações vinculadas ao processo.",
			"Registro de divergências ou mudanças de status que precisem de revisão.",
		},
		Process: []string{
			"A empresa informa ou importa os dados necessários para iniciar o cadastro.",
			"O sistema organiza a identidade usada como referência para as demais consultas.",
			"Informações de fontes e validações são associadas ao mesmo processo.",
			"Divergências e resultados ficam disponíveis para análise conforme as regras da operação.",
		},
		Interpretation: "Dados cadastrais ajudam a estabelecer quem está sendo analisado e a organizar evidências relacionadas. Uma divergência não deve ser tratada automaticamente como fraude: ela pode exigir conferência da origem, atualização dos dados ou validação adicional.",
		Limitations: []string{
			"Abrangência e atualização dependem das fontes e integrações contratadas.",
			"Informações desatualizadas ou digitadas incorretamente podem gerar divergências que exigem revisão.",
			"Cadastro estruturado apoia a decisão, mas não substitui critérios de risco, identidade ou documentos quando eles forem necessários.",
		},
		RelatedSolutionName: "Cargo Score",
		RelatedSolutionPath: "/solucoes/pesquisa-cadastral-de-motoristas",
		FrequentlyAsked: []site.FAQ{
			{Question: "Dados cadastrais são o mesmo que pesquisa cadastral?", Answer: "Não. Os dados cadastrais são uma parte da pesquisa. A pesquisa cadastral pode combinar identidade, documentos, registros, contexto de risco e políticas operacionais."},
			{Question: "Uma divergência cadastral reprova automaticamente?", Answer: "Não necessariamente. A interpretação depende da origem da informação, das regras da empresa e da necessidade de conferência ou validação adicional."},
			{Question: "Os dados podem ser combinados com biometria?", Answer: "Sim. No Cargo Score, validações de identidade podem ser vinculadas ao mesmo processo cadastral."},
		},
	},
	{
		Slug:            "autenticacao-de-identidade",
		Category:        "Identidade",
		Subject:         "Pessoa",
		Name:            "Autenticação de identidade",
		Icon:            "shield-check",
		Title:           "Autenticação de identidade: como confirmar motoristas em etapas sensíveis",
		MetaDescription: "Entenda como a autenticação de identidade pode ser usada antes de pagamentos, alterações cadastrais e outras etapas sensíveis no transporte.",
		Lead:            "Autenticação de identidade adiciona uma confirmação antes de uma ação sensível, reduzindo a dependência de mensagens, contatos ou dados recebidos por intermediários.",
		Definition:      "Autenticação de identidade é uma etapa criada para confirmar que a pessoa que está realizando uma ação corresponde à identidade apresentada. Ela pode combinar um link individual, biometria facial e contexto do acesso antes de liberar o próximo passo do processo.",
		Purpose:         "No transporte, a autenticação é especialmente útil quando uma operação precisa elevar o nível de confiança antes de adiantamentos, alterações de dados, cadastros ou compartilhamento de informações sensíveis.",
		Scope: []string{
			"Criação de uma jornada individual vinculada ao processo e à identidade informada.",
			"Confirmação facial e prova de vida quando previstas no fluxo.",
			"Registro de contexto do acesso aplicável à autenticação.",
			"Retorno do status diretamente ao ambiente usado pela empresa contratante.",
		},
		Process: []string{
			"A empresa solicita uma autenticação antes da etapa sensível.",
			"A pessoa acessa o link individual e realiza as validações previstas.",
			"O resultado é devolvido ao canal oficial ou sistema da contratante.",
			"A empresa decide se prossegue com a ação conforme sua política e o contexto disponível.",
		},
		Interpretation: "Uma autenticação aprovada aumenta a confiança de que a pessoa validada participou da jornada. Ela não confirma, por si só, titularidade de conta bancária, legitimidade de todo dado externo nem ausência absoluta de fraude.",
		Limitations: []string{
			"A autenticação é uma camada de proteção e não uma garantia absoluta contra fraude.",
			"A decisão de liberar pagamento ou alteração continua sendo responsabilidade do processo da contratante.",
			"Dados financeiros ou informações externas precisam de controles próprios quando fizerem parte da operação.",
		},
		RelatedSolutionName: "Cargo Autenticador",
		RelatedSolutionPath: "/solucoes/autenticador-de-seguranca",
		FrequentlyAsked: []site.FAQ{
			{Question: "Autenticação de identidade é uma pesquisa cadastral completa?", Answer: "Não. O objetivo principal é confirmar identidade antes de uma etapa sensível. Outras consultas podem ser adicionadas quando fizerem parte do processo contratado."},
			{Question: "A autenticação confirma a conta bancária do motorista?", Answer: "Não por si só. A autenticação confirma a participação da pessoa validada na jornada; titularidade bancária exige controles ou fontes específicas."},
			{Question: "Quando faz sentido autenticar novamente?", Answer: "Quando a empresa define que uma ação possui risco suficiente para exigir uma nova confirmação, como uma alteração importante ou uma etapa financeira sensível."},
		},
	},
	{
		Slug:            "telefone-contexto-acesso",
		Category:        "Identidade",
		Subject:         "Pessoa",
		Name:            "Telefone e contexto do acesso",
		Icon:            "smartphone",
		Title:           "Telefone e contexto do acesso: como apoiar validações de identidade",
		MetaDescription: "Entenda como telefone, localização e contexto do dispositivo podem complementar a validação de identidade de motoristas e usuários.",
		Lead:            "Telefone e contexto do acesso funcionam como sinais complementares para relacionar o contato usado na operação à jornada que está sendo concluída.",
		Definition:      "Analisar telefone e contexto do acesso significa observar informações do contato e da sessão que podem ajudar a conferir se a jornada é coerente com o cadastro e com a operação. Dependendo do fluxo, isso pode incluir o número informado e informações de localização ou dispositivo aplicáveis ao processo.",
		Purpose:         "Esses sinais ajudam a identificar divergências, mudanças de contato e situações em que a pessoa que conclui a jornada pode não estar usando o mesmo contexto informado durante a contratação ou cadastro.",
		Scope: []string{
			"Telefone informado ou associado ao processo de contratação e cadastro.",
			"Comparação do contato usado na jornada com os dados disponíveis no processo.",
			"Localização obtida com permissão quando prevista na jornada.",
			"Informações de dispositivo ou sessão disponíveis e aplicáveis ao fluxo contratado.",
		},
		Process: []string{
			"O cadastro registra o contato utilizado para iniciar ou conduzir o processo.",
			"A pessoa acessa a jornada individual pelo dispositivo disponível.",
			"O sistema registra os sinais de contexto previstos e autorizados.",
			"Divergências ficam disponíveis para conferência junto com identidade e demais evidências.",
		},
		Interpretation: "Telefone, localização e dispositivo são sinais contextuais. Nenhum deles comprova sozinho a identidade da pessoa ou a titularidade da linha; o valor está na combinação com biometria, cadastro e outras verificações.",
		Limitations: []string{
			"Números de telefone podem ser compartilhados, transferidos ou reutilizados e não devem ser tratados como prova isolada de identidade.",
			"Localização depende de permissão, disponibilidade técnica e condições do dispositivo.",
			"Contexto do acesso deve ser coletado apenas quando necessário e compatível com a finalidade do processo.",
		},
		RelatedSolutionName: "Cargo Score",
		RelatedSolutionPath: "/solucoes/pesquisa-cadastral-de-motoristas",
		FrequentlyAsked: []site.FAQ{
			{Question: "O número de telefone prova quem é o motorista?", Answer: "Não. O telefone é um sinal de contexto e deve ser combinado com verificações de identidade quando a operação precisar confirmar a pessoa."},
			{Question: "A localização é sempre coletada?", Answer: "Não. A coleta depende da jornada configurada, da finalidade aplicável e da permissão necessária no dispositivo."},
			{Question: "Por que comparar o contexto do acesso?", Answer: "Porque divergências entre cadastro, contato e jornada podem indicar a necessidade de uma conferência adicional antes de uma decisão sensível."},
		},
	},
	{
		Slug:            "cnh-informacoes-habilitacao",
		Category:        "Documentos e risco",
		Subject:         "Risco",
		Name:            "CNH e informações da habilitação",
		Icon:            "badge-check",
		Title:           "CNH e informações da habilitação: o que analisar em motoristas",
		MetaDescription: "Entenda como informações da CNH podem compor a análise cadastral de motoristas e por que o resultado deve ser interpretado no contexto da operação.",
		Lead:            "Informações da habilitação ajudam a contextualizar o cadastro do motorista e podem compor regras operacionais antes da liberação de uma viagem ou contratação.",
		Definition:      "A análise de CNH organiza informações da habilitação disponíveis nas fontes contratadas e as relaciona ao motorista que está sendo pesquisado. Ela pode apoiar a conferência de situação, atributos e dados relevantes para a política da operação.",
		Purpose:         "O objetivo é evitar que a equipe trate a CNH como uma consulta isolada e permitir que as informações da habilitação sejam avaliadas junto com identidade, cadastro, ANTT, contexto judicial e demais critérios aplicáveis.",
		Scope: []string{
			"Identificação do documento e associação ao motorista pesquisado.",
			"Situação e atributos da habilitação disponibilizados pela fonte consultada.",
			"Datas, categorias ou registros relevantes quando presentes no retorno contratado.",
			"Aplicação de regras definidas pela operação sobre as informações disponíveis.",
		},
		Process: []string{
			"O motorista é identificado dentro do processo cadastral.",
			"A consulta de habilitação é realizada conforme as fontes disponíveis no projeto.",
			"O retorno é organizado com origem e status dentro da mesma análise.",
			"A equipe interpreta o resultado de acordo com a finalidade e os critérios aplicáveis à operação.",
		},
		Interpretation: "O retorno da CNH é uma fonte de informação para apoiar a análise. O significado operacional depende dos atributos retornados, da atualização da fonte e das regras válidas para aquela contratação ou viagem.",
		Limitations: []string{
			"Campos, abrangência e atualização dependem da fonte consultada e do escopo contratado.",
			"Uma consulta não deve ser tratada como substituta de obrigações legais ou verificações oficiais exigidas pela operação.",
			"Regras de habilitação precisam ser definidas e revisadas conforme a finalidade real do processo.",
		},
		RelatedSolutionName: "Cargo Score",
		RelatedSolutionPath: "/solucoes/pesquisa-cadastral-de-motoristas",
		FrequentlyAsked: []site.FAQ{
			{Question: "A consulta de CNH aprova ou reprova automaticamente?", Answer: "Não necessariamente. O retorno fornece informações que podem ser avaliadas por regras operacionais ou por análise humana, conforme o processo da empresa."},
			{Question: "Quais informações da habilitação aparecem?", Answer: "A disponibilidade de campos depende da fonte e da contratação. A página não pressupõe que todos os atributos estejam disponíveis em todos os projetos."},
			{Question: "A CNH pode ser analisada junto com ANTT e cadastro?", Answer: "Sim. No Cargo Score, diferentes sinais podem ser reunidos no mesmo processo para evitar consultas desconectadas."},
		},
	},
	{
		Slug:            "antt-rntrc",
		Category:        "Documentos e risco",
		Subject:         "Risco",
		Name:            "ANTT e RNTRC",
		Icon:            "route",
		Title:           "ANTT e RNTRC: o que são e como entram na análise de transporte",
		MetaDescription: "Entenda o papel da ANTT e do RNTRC na análise cadastral de operações rodoviárias e como essas informações podem ser combinadas com outros critérios.",
		Lead:            "Informações da ANTT e do RNTRC ajudam a contextualizar o registro do transportador dentro de uma análise de transporte rodoviário de cargas.",
		Definition:      "A ANTT é a Agência Nacional de Transportes Terrestres. O RNTRC é o Registro Nacional de Transportadores Rodoviários de Cargas. Em uma análise cadastral, informações disponíveis sobre esse registro podem ser associadas ao processo para apoiar a conferência do contexto de transporte.",
		Purpose:         "A consulta permite organizar informações regulatórias relevantes junto com identidade, CNH, veículo e regras da operação, reduzindo a necessidade de conferir cada fonte separadamente.",
		Scope: []string{
			"Informações cadastrais do RNTRC disponibilizadas pela fonte contratada.",
			"Associação do registro ao contexto da pessoa, empresa ou operação pesquisada quando aplicável.",
			"Status e atributos retornados pela integração ou fonte consultada.",
			"Aplicação de critérios operacionais sobre as informações efetivamente disponíveis.",
		},
		Process: []string{
			"A operação identifica a pessoa ou entidade que precisa ser analisada.",
			"O sistema consulta as informações da ANTT/RNTRC previstas no projeto.",
			"O retorno é vinculado ao mesmo processo cadastral e preserva seu contexto.",
			"A equipe avalia o resultado junto com os demais requisitos da operação.",
		},
		Interpretation: "O RNTRC é um elemento de contexto regulatório e cadastral. Um retorno isolado não demonstra, por si só, que todos os requisitos legais, contratuais ou operacionais de uma viagem estão atendidos.",
		Limitations: []string{
			"A disponibilidade e atualização das informações dependem das fontes integradas e do momento da consulta.",
			"A consulta não substitui obrigações de conferência oficial que sejam exigidas por lei, contrato ou política interna.",
			"O significado de cada situação deve ser relacionado à categoria de transporte e ao contexto real da operação.",
		},
		RelatedSolutionName: "Cargo Score",
		RelatedSolutionPath: "/solucoes/pesquisa-cadastral-de-motoristas",
		FrequentlyAsked: []site.FAQ{
			{Question: "O que significa RNTRC?", Answer: "RNTRC significa Registro Nacional de Transportadores Rodoviários de Cargas, administrado pela ANTT."},
			{Question: "Consultar RNTRC substitui outras análises?", Answer: "Não. O registro pode ser um dos sinais avaliados junto com identidade, habilitação, veículo e critérios da operação."},
			{Question: "Os dados da ANTT são iguais em todos os projetos?", Answer: "Não necessariamente. Campos e disponibilidade dependem das fontes, integrações e escopo contratado."},
		},
	},
	{
		Slug:            "processos-contexto-judicial",
		Category:        "Documentos e risco",
		Subject:         "Risco",
		Name:            "Processos e contexto judicial",
		Icon:            "file-warning",
		Title:           "Processos e contexto judicial: como usar na análise cadastral",
		MetaDescription: "Entenda como informações judiciais podem compor uma análise cadastral, por que homônimos exigem cuidado e por que o contexto não deve gerar decisão automática.",
		Lead:            "Informações sobre processos podem acrescentar contexto à pesquisa cadastral, mas precisam ser relacionadas corretamente à pessoa e interpretadas conforme finalidade e política da operação.",
		Definition:      "Análise de processos e contexto judicial é a organização de informações judiciais retornadas por fontes contratadas para apoiar a compreensão do cadastro. O objetivo não é transformar a existência de um registro em uma conclusão automática, mas disponibilizar contexto para uma avaliação responsável.",
		Purpose:         "Quando a operação utiliza esse tipo de informação, o valor está em reunir origem, identificação, status e contexto no mesmo processo, permitindo revisão e evitando decisões baseadas apenas em uma ocorrência desconectada.",
		Scope: []string{
			"Registros judiciais retornados pelas fontes previstas no projeto.",
			"Origem, identificação e informações de contexto disponibilizadas pela consulta.",
			"Sinalização de possíveis divergências de identidade ou homônimos que exijam conferência.",
			"Associação do retorno às políticas e critérios definidos para a finalidade da análise.",
		},
		Process: []string{
			"A consulta é vinculada à pessoa identificada no processo cadastral.",
			"As fontes retornam os registros e dados de contexto disponíveis.",
			"O sistema organiza o resultado para facilitar conferência, inclusive de possíveis homônimos.",
			"A equipe aplica os critérios adequados à finalidade e registra a decisão no contexto da análise.",
		},
		Interpretation: "A existência de processo judicial não deve ser tratada como sinônimo automático de risco, culpa ou impedimento. Natureza do registro, identidade correta, situação e finalidade do uso precisam ser considerados antes de qualquer conclusão.",
		Limitations: []string{
			"Homônimos e correspondências incompletas podem exigir validação adicional de identidade.",
			"Situação processual e conteúdo podem mudar; atualização depende da fonte consultada.",
			"O uso de informações judiciais deve respeitar finalidade, proporcionalidade, legislação aplicável e política definida pela contratante.",
		},
		RelatedSolutionName: "Cargo Score",
		RelatedSolutionPath: "/solucoes/pesquisa-cadastral-de-motoristas",
		FrequentlyAsked: []site.FAQ{
			{Question: "Ter um processo judicial significa reprovação?", Answer: "Não. A existência de um registro precisa ser contextualizada e não deve ser convertida automaticamente em conclusão sobre a pessoa."},
			{Question: "Como lidar com possíveis homônimos?", Answer: "A correspondência precisa ser conferida com os identificadores e informações disponíveis. Quando houver dúvida, o resultado deve ser tratado como pendente de revisão."},
			{Question: "A Viagate toma a decisão jurídica?", Answer: "Não. A plataforma organiza informações para apoiar o processo da contratante; não substitui análise jurídica ou decisão humana quando elas forem necessárias."},
		},
	},
	{
		Slug:            "politicas-criterios-operacionais",
		Category:        "Documentos e risco",
		Subject:         "Risco",
		Name:            "Políticas e critérios operacionais",
		Icon:            "sliders",
		Title:           "Políticas e critérios operacionais: como padronizar análises de risco",
		MetaDescription: "Entenda como políticas e critérios operacionais transformam consultas dispersas em uma análise padronizada, revisável e alinhada à finalidade da operação.",
		Lead:            "Políticas operacionais definem como a empresa interpreta os sinais disponíveis e quais situações exigem aprovação, atenção, revisão ou outra tratativa.",
		Definition:      "Políticas e critérios operacionais são regras configuradas para organizar a interpretação das informações usadas em uma análise. Elas conectam dados cadastrais, documentos e contexto à forma como a empresa conduz o próprio processo de decisão.",
		Purpose:         "A principal função é reduzir decisões inconsistentes entre analistas e operações, tornando visível quais critérios foram aplicados e permitindo revisão quando dados ou regras mudarem.",
		Scope: []string{
			"Critérios definidos de acordo com perfil, finalidade e necessidade da operação.",
			"Regras aplicadas aos sinais e informações efetivamente disponíveis no processo.",
			"Status ou alertas usados para orientar análise humana e tratativas internas.",
			"Histórico de mudanças, reanálises e contexto da decisão quando suportado pelo produto.",
		},
		Process: []string{
			"A empresa define quais informações são relevantes para o processo.",
			"Os critérios são parametrizados conforme o escopo e a política operacional aplicável.",
			"As consultas e validações alimentam a análise com os sinais disponíveis.",
			"O resultado é apresentado com contexto para aprovação, atenção ou revisão pela operação.",
		},
		Interpretation: "Uma política automatiza critérios previamente definidos, não a responsabilidade da empresa sobre a decisão. Regras precisam ser compreensíveis, proporcionais à finalidade e revisadas quando o processo ou o contexto mudar.",
		Limitations: []string{
			"Uma regra só é adequada se os dados usados forem relevantes e suficientemente atualizados para a finalidade.",
			"Políticas não devem transformar sinais incompletos em conclusões que o dado não suporta.",
			"Critérios podem variar entre operações, clientes, contratos e requisitos aplicáveis; não existe uma regra universal para todos os cenários.",
		},
		RelatedSolutionName: "Cargo Score",
		RelatedSolutionPath: "/solucoes/pesquisa-cadastral-de-motoristas",
		FrequentlyAsked: []site.FAQ{
			{Question: "As regras são iguais para todas as empresas?", Answer: "Não. Os critérios podem variar conforme finalidade, perfil operacional e escopo contratado."},
			{Question: "Políticas operacionais eliminam a análise humana?", Answer: "Não necessariamente. Elas ajudam a padronizar critérios e podem indicar casos que exigem revisão ou decisão humana."},
			{Question: "É possível revisar uma política depois?", Answer: "Sim. Critérios precisam acompanhar mudanças de processo e devem ser revistos quando deixarem de representar a finalidade ou o risco da operação."},
		},
	},
	{
		Slug:            "historico-veicular",
		Category:        "Operação e veículo",
		Subject:         "Veículo",
		Name:            "Histórico veicular",
		Icon:            "car-front",
		Title:           "Histórico veicular: o que é e quais informações podem compor a análise",
		MetaDescription: "Entenda o que é histórico veicular, quais registros podem aparecer conforme a fonte e como essas informações apoiam prevenção e análise operacional.",
		Lead:            "Histórico veicular reúne informações cadastrais, documentais e registros relevantes para formar uma visão mais completa do veículo antes ou durante a operação.",
		Definition:      "Histórico veicular é o conjunto de informações disponíveis sobre o cadastro e os registros de um veículo. Dependendo das fontes contratadas, a análise pode reunir situação documental, restrições e indicadores históricos em um dossiê voltado à prevenção.",
		Purpose:         "O objetivo é reduzir conferências fragmentadas e permitir que a equipe visualize registros relevantes do veículo junto com pendências, critérios e tratativas necessárias.",
		Scope: []string{
			"Dados cadastrais e características do veículo disponibilizados pelas fontes consultadas.",
			"Situação documental e restrições retornadas no projeto contratado.",
			"Indicadores históricos, como registros de sinistro, leilão, gravame ou bloqueio, quando disponíveis.",
			"Organização do histórico junto com multas, débitos e outras pendências aplicáveis.",
		},
		Process: []string{
			"O veículo é identificado por placa ou pelos dados previstos no processo.",
			"As fontes contratadas retornam as informações disponíveis para o cadastro.",
			"O sistema organiza registros e pendências em uma visão de prevenção.",
			"A equipe prioriza a tratativa conforme a relevância de cada informação para a operação.",
		},
		Interpretation: "Histórico veicular descreve registros disponíveis sobre o veículo e não representa, sozinho, uma avaliação física atual. Um veículo sem determinada ocorrência em uma fonte também não deve ser considerado automaticamente livre de qualquer risco.",
		Limitations: []string{
			"Abrangência, atualização e existência de cada indicador dependem da fonte consultada.",
			"Histórico de registros não substitui inspeção mecânica, checklist ou avaliação física do veículo.",
			"Cada ocorrência precisa ser interpretada conforme data, origem e relevância para a finalidade da operação.",
		},
		RelatedSolutionName: "Prevenção Veicular",
		RelatedSolutionPath: "/solucoes/prevencao-veicular",
		FrequentlyAsked: []site.FAQ{
			{Question: "Histórico veicular é uma inspeção do caminhão?", Answer: "Não. A análise organiza registros e informações disponíveis em fontes; condição física exige inspeção ou outro processo específico."},
			{Question: "Todos os indicadores aparecem em todos os veículos?", Answer: "Não. A disponibilidade depende das fontes contratadas, do tipo de registro e da existência de informação para o veículo consultado."},
			{Question: "Histórico e multas podem ficar na mesma análise?", Answer: "Sim. Na Prevenção Veicular, diferentes pendências e registros podem ser organizados no mesmo dossiê conforme o escopo do projeto."},
		},
	},
	{
		Slug:            "multas-debitos-restricoes",
		Category:        "Operação e veículo",
		Subject:         "Veículo",
		Name:            "Multas, débitos e restrições",
		Icon:            "receipt",
		Title:           "Multas, débitos e restrições de veículos: como organizar a análise",
		MetaDescription: "Veja como multas, débitos, licenciamento e restrições podem ser centralizados para tratamento preventivo de veículos e frotas.",
		Lead:            "Multas, débitos e restrições deixam de ser ocorrências isoladas quando são reunidos em um processo que permite identificar prioridade, prazo e necessidade de tratativa.",
		Definition:      "A análise de multas, débitos e restrições reúne pendências veiculares disponibilizadas pelas fontes contratadas para apoiar prevenção e acompanhamento. O objetivo é tornar visível o que precisa ser conferido ou tratado antes que a pendência gere impacto operacional.",
		Purpose:         "Centralizar essas informações ajuda a equipe a acompanhar veículos de forma preventiva e reduz a dependência de consultas manuais realizadas somente quando surge um problema.",
		Scope: []string{
			"Multas e ocorrências disponibilizadas nas fontes integradas.",
			"Débitos e obrigações, como IPVA ou licenciamento, quando presentes no retorno contratado.",
			"Restrições, bloqueios ou pendências documentais disponibilizadas para o veículo.",
			"Prazos, valores, status e registros de tratativa quando suportados pelo fluxo operacional.",
		},
		Process: []string{
			"O veículo é cadastrado ou selecionado para a consulta preventiva.",
			"As fontes retornam as pendências e informações disponíveis no momento da consulta.",
			"O sistema organiza os itens por status e contexto para facilitar a priorização.",
			"A equipe acompanha a tratativa e realiza novas conferências conforme a necessidade operacional.",
		},
		Interpretation: "Uma pendência indica uma informação que precisa ser compreendida ou tratada. Valor, prazo, origem e situação devem ser conferidos antes de qualquer ação, especialmente quando a fonte pode sofrer atualização entre consultas.",
		Limitations: []string{
			"Disponibilidade e atualização dependem dos órgãos, fontes e integrações utilizados no projeto.",
			"A plataforma organiza informações, mas não substitui o sistema oficial do órgão responsável para atos que exijam confirmação formal.",
			"Ausência de um item em determinada consulta não é garantia permanente de inexistência de novas pendências.",
		},
		RelatedSolutionName: "Prevenção Veicular",
		RelatedSolutionPath: "/solucoes/prevencao-veicular",
		FrequentlyAsked: []site.FAQ{
			{Question: "A consulta mostra multas e débitos em tempo real?", Answer: "A atualização depende da fonte integrada e do momento em que ela disponibiliza a informação. O sistema deve apresentar o retorno conforme a origem consultada."},
			{Question: "A Viagate realiza o pagamento das pendências?", Answer: "A solução é voltada à consulta, organização e acompanhamento preventivo. Tratativas financeiras dependem do processo definido pela empresa e pelos canais oficiais aplicáveis."},
			{Question: "É possível acompanhar uma frota?", Answer: "A Prevenção Veicular foi desenhada para organizar informações de veículos e pode apoiar rotinas recorrentes de acompanhamento conforme o projeto contratado."},
		},
	},
	{
		Slug:            "monitoramento-alertas",
		Category:        "Operação e veículo",
		Subject:         "Veículo",
		Name:            "Monitoramento e alertas",
		Icon:            "map-pinned",
		Title:           "Monitoramento e alertas de veículos: como acompanhar eventos da operação",
		MetaDescription: "Entenda como posições e alertas de rastreadores, iscas e parceiros de monitoramento podem ser integrados ao contexto de veículos e viagens.",
		Lead:            "Monitoramento reúne posições e eventos de fontes compatíveis para que a equipe acompanhe veículos e viagens dentro do contexto operacional da Plataforma Cargo.",
		Definition:      "Monitoramento e alertas correspondem ao acompanhamento de posições e eventos disponibilizados por rastreadores, iscas ou parceiros integrados. A Viagate pode conectar essas fontes ao cadastro do veículo e à viagem para organizar o acompanhamento no mesmo ambiente operacional.",
		Purpose:         "O valor da integração está em relacionar o evento de monitoramento ao veículo e à operação correta, permitindo que a equipe interprete alertas sem perder o contexto da viagem.",
		Scope: []string{
			"Posições disponibilizadas pelas integrações de monitoramento compatíveis.",
			"Alertas e eventos fornecidos pelo equipamento ou parceiro integrado.",
			"Vínculo do acompanhamento a veículos fixos ou viagens específicas, conforme a modalidade contratada.",
			"Uso complementar do Cargo Truck quando a operação precisar registrar eventos pelo aplicativo do motorista.",
		},
		Process: []string{
			"A fonte de rastreamento ou monitoramento compatível é integrada ao ambiente.",
			"O veículo ou viagem é associado aos dados recebidos da fonte.",
			"Posições e eventos ficam disponíveis para acompanhamento conforme a integração.",
			"A equipe interpreta alertas e atua conforme os critérios definidos para a operação.",
		},
		Interpretation: "Um alerta representa um evento informado pela fonte de monitoramento e precisa ser interpretado dentro do contexto da viagem. Tipo, precisão e significado dependem do equipamento, parceiro e configuração usados no projeto.",
		Limitations: []string{
			"Continuidade, precisão e frequência dos dados dependem do rastreador, da isca, do parceiro e da conectividade disponível.",
			"A Viagate não deve ser apresentada como fonte universal de telemetria quando o dado é fornecido por integrações externas.",
			"Monitoramento reduz lacunas de acompanhamento, mas não garante prevenção de todo evento de risco ou perda de sinal.",
		},
		RelatedSolutionName: "Monitoramento de veículos",
		RelatedSolutionPath: "/solucoes/monitoramento-de-veiculos",
		FrequentlyAsked: []site.FAQ{
			{Question: "A Viagate funciona com qualquer rastreador?", Answer: "A disponibilidade depende das integrações compatíveis e do projeto técnico. Não se deve pressupor compatibilidade universal."},
			{Question: "O Cargo Truck substitui o rastreador?", Answer: "Não necessariamente. O aplicativo pode complementar o acompanhamento operacional, enquanto necessidades de rastreamento específico dependem da tecnologia e da política da operação."},
			{Question: "O que um alerta significa?", Answer: "O significado depende da fonte e da configuração que gerou o evento. Por isso, o alerta precisa ser analisado junto com o veículo, a viagem e os critérios definidos pela empresa."},
		},
	},
	{
		Slug:            "viagem-contexto-operacional",
		Category:        "Operação e veículo",
		Subject:         "Veículo",
		Name:            "Viagem e contexto operacional",
		Icon:            "route",
		Title:           "Viagem e contexto operacional: como organizar eventos do motorista e da carga",
		MetaDescription: "Entenda como coletas, entregas, posições, paradas e comprovantes formam o contexto operacional de uma viagem conectada.",
		Lead:            "Contexto operacional organiza o que acontece durante a viagem para que atividades, posições, paradas e comprovantes não fiquem espalhados em ligações e mensagens.",
		Definition:      "Viagem e contexto operacional correspondem ao conjunto de atividades e eventos registrados durante a execução de um transporte. No Cargo Truck, o smartphone do motorista se conecta à Plataforma Cargo para receber tarefas e registrar acontecimentos relacionados à viagem.",
		Purpose:         "A estrutura cria uma linha do tempo que ajuda a operação a acompanhar execução, conferir etapas e reconstruir o que aconteceu entre coleta e entrega.",
		Scope: []string{
			"Atividades de coleta e entrega distribuídas ao motorista.",
			"Posições registradas durante a execução quando previstas no fluxo.",
			"Eventos de parada, como descanso, abastecimento ou manutenção, conforme a configuração da operação.",
			"Comprovantes e registros relacionados à conclusão das atividades disponíveis no aplicativo.",
		},
		Process: []string{
			"A empresa cria ou distribui a viagem e suas atividades pela plataforma.",
			"O motorista recebe as instruções no Cargo Truck e inicia a execução.",
			"Eventos e atualizações são registrados ao longo da viagem conforme o fluxo configurado.",
			"A equipe acompanha o andamento e mantém uma linha do tempo para revisão posterior.",
		},
		Interpretation: "O contexto operacional descreve os eventos registrados no fluxo e deve ser lido de acordo com a origem de cada informação. Ele ajuda a reconstruir a viagem, mas não transforma automaticamente todo evento em evidência conclusiva sobre responsabilidade ou risco.",
		Limitations: []string{
			"A qualidade do histórico depende das atividades configuradas, do dispositivo, da conectividade e dos registros efetivamente realizados.",
			"O Cargo Truck é uma camada operacional e não deve ser descrito como substituto universal de rastreamento satelital ou telemetria dedicada.",
			"Requisitos específicos de seguradoras, apólices ou políticas de risco precisam ser avaliados para cada operação.",
		},
		RelatedSolutionName: "Cargo Truck",
		RelatedSolutionPath: "/solucoes/gestao-logistica",
		FrequentlyAsked: []site.FAQ{
			{Question: "Quais eventos podem fazer parte da viagem?", Answer: "O fluxo pode incluir coletas, entregas, posições, paradas e comprovantes conforme as funções e configurações disponíveis para a operação."},
			{Question: "A empresa acompanha o que o motorista registra?", Answer: "Sim. O Cargo Truck conecta o aplicativo do motorista à Plataforma Cargo para que atividades e eventos possam ser acompanhados pela operação."},
			{Question: "O aplicativo pode ser combinado com Cargo Score?", Answer: "Sim. A viagem pode ser combinada a processos de análise cadastral quando a operação precisar de controle adicional antes ou durante a execução."},
		},
	},
}

func Analyses() []site.AnalysisReference {
	return analyses
}

func FindAnalysis(slug string) (site.AnalysisReference, bool) {
	for _, analysis := range analyses {
		if analysis.Slug == slug {
			return analysis, true
		}
	}
	return site.AnalysisReference{}, false
}

func RelatedAnalyses(current site.AnalysisReference) []site.AnalysisReference {
	related := make([]site.AnalysisReference, 0, 3)
	for _, analysis := range analyses {
		if analysis.Slug == current.Slug || analysis.Category != current.Category {
			continue
		}
		related = append(related, analysis)
		if len(related) == 3 {
			break
		}
	}
	return related
}
