// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/viagate/site/internal/site"
	"github.com/viagate/site/web/components"
)

func About(meta site.PageMeta) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"page-hero\"><div class=\"container hero-grid\"><div class=\"hero-copy\"><span class=\"eyebrow\">Sobre a Viagate</span><h1>Tecnologia brasileira para decisões críticas no transporte</h1><p class=\"hero-lead\">Conectamos identidade, pesquisa cadastral, prevenção e logística para transformar dados dispersos em processos rastreáveis.</p></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.ImagePlaceholder("Equipe multidisciplinar da Viagate reunida em um ambiente de tecnologia e logística, com telas de produto ao fundo.", "1600 x 1400 px - proporção 8:7", "hero-image").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div></section><section class=\"section\"><div class=\"container split-content\"><div><span class=\"eyebrow\">Nossa perspectiva</span><h2>Uma decisão não termina quando o cadastro é aprovado</h2><p>A identidade influencia a contratação. A autenticação protege etapas sensíveis. Os eventos da viagem preservam o contexto da decisão inicial.</p><p>Por isso, a Viagate desenvolve produtos modulares que resolvem problemas específicos e podem compartilhar informações dentro de uma operação integrada.</p></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.ImagePlaceholder("Diagrama editorial conectando identidade, risco, prevenção a fraudes, viagens e integrações.", "1600 x 1200 px - proporção 4:3", "content-image").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div></section><section class=\"section section-muted\"><div class=\"container values-grid\"><article><span>01</span><h2>Clareza</h2><p>Informação compreensível para decisões humanas e processos auditáveis.</p></article><article><span>02</span><h2>Integração</h2><p>Tecnologia que se adapta ao fluxo, sem criar ilhas operacionais.</p></article><article><span>03</span><h2>Responsabilidade</h2><p>Segurança, privacidade e finalidade consideradas desde o desenho da solução.</p></article><article><span>04</span><h2>Evolução</h2><p>Produtos modulares preparados para acompanhar novas necessidades.</p></article></div></section>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.CallToAction("Veja a tecnologia Viagate em funcionamento", "Agende uma demonstração para conhecer os produtos e discutir o seu cenário operacional.").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = components.Layout(meta).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
