// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/viagate/site/internal/site"
	"github.com/viagate/site/web/components"
)

func Contact(meta site.PageMeta, status string, interest string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"page-hero contact-hero\"><div class=\"container contact-layout\"><div class=\"contact-copy\"><span class=\"eyebrow\">Fale com a Viagate</span><h1>Agende uma demonstração para o seu cenário operacional</h1><p>Conte qual processo precisa de mais controle. A equipe Viagate apresentará os produtos e integrações aplicáveis à sua operação.</p><div class=\"contact-points\"><div><strong>E-mail</strong><a href=\"mailto:contato@viagate.com.br\">contato@viagate.com.br</a></div><div><strong>Telefone</strong><a href=\"tel:+5541999623600\">+55 41 99962-3600</a></div><div><strong>Localização</strong><span>Curitiba, Paraná, Brasil</span></div></div></div><div class=\"contact-form-card\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if status == "sent" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"form-alert form-alert-success\" role=\"status\"><strong>Mensagem enviada.</strong><span>A equipe Viagate retornará assim que possível.</span></div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			if status == "invalid" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<div class=\"form-alert form-alert-error\" role=\"alert\"><strong>Revise os dados.</strong><span>Preencha nome, e-mail válido e aceite a política de privacidade.</span></div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			if status == "limited" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<div class=\"form-alert form-alert-error\" role=\"alert\"><strong>Muitas tentativas.</strong><span>Aguarde alguns minutos antes de enviar novamente.</span></div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			if status == "unavailable" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<div class=\"form-alert form-alert-error\" role=\"alert\"><strong>Envio temporariamente indisponível.</strong><span>Escreva para contato@viagate.com.br.</span></div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<form action=\"/contato\" method=\"post\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if interest != "" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "<input type=\"hidden\" name=\"interest\" value=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var3 string
				templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(interest)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/pages/contact.templ`, Line: 33, Col: 60}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "<div class=\"form-row\"><label>Nome completo<input type=\"text\" name=\"name\" autocomplete=\"name\" minlength=\"2\" maxlength=\"100\" required></label><label>E-mail profissional<input type=\"email\" name=\"email\" autocomplete=\"email\" maxlength=\"254\" required></label></div><div class=\"form-row\"><label>Empresa<input type=\"text\" name=\"company\" autocomplete=\"organization\" maxlength=\"120\"></label><label>Telefone<input type=\"tel\" name=\"phone\" autocomplete=\"tel\" maxlength=\"40\"></label></div><label>Como podemos ajudar?<textarea name=\"message\" rows=\"5\" maxlength=\"3000\"></textarea></label> <label class=\"honeypot\" aria-hidden=\"true\">Website<input type=\"text\" name=\"website\" tabindex=\"-1\" autocomplete=\"off\"></label> <label class=\"consent\"><input type=\"checkbox\" name=\"consent\" required><span>Concordo com o tratamento dos dados para retorno deste contato, conforme a <a href=\"/termos-uso-politica-privacidade#politica-de-privacidade\">Política de Privacidade</a>.</span></label> <button class=\"button\" type=\"submit\">Solicitar demonstração</button></form></div></div></section>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = components.Layout(meta).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
