// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/viagate/site/internal/site"
	"github.com/viagate/site/web/components"
)

func Home(meta site.PageMeta, solutions []site.Solution, articles []site.Article) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"command-hero\"><div class=\"command-grid\" aria-hidden=\"true\"></div><div class=\"command-glow command-glow-left\" aria-hidden=\"true\"></div><div class=\"command-glow command-glow-right\" aria-hidden=\"true\"></div><div class=\"container command-hero-grid\"><div class=\"command-copy\"><div class=\"authority-line\"><span class=\"authority-dot\"></span> Tecnologia para operações de transporte de alta criticidade</div><h1>Controle o risco <span>antes que ele alcance a operação.</span></h1><p>A Viagate conecta identidade, pesquisa cadastral, prevenção a fraudes e logística em uma infraestrutura única, rastreável e pronta para integrar.</p><div class=\"hero-actions\"><a class=\"button\" href=\"/contato\">Apresente o seu cenário</a> <a class=\"button button-dark-ghost\" href=\"/solucoes\">Explorar o ecossistema</a></div><ul class=\"command-principles\" aria-label=\"Princípios da plataforma\"><li><span>01</span> Identidade confirmada</li><li><span>02</span> Critérios parametrizáveis</li><li><span>03</span> Evidências rastreáveis</li></ul></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.CommandCenter().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div><div class=\"container command-capabilities\"><div><span>Identidade</span><strong>Biometria e prova de vida</strong></div><div><span>Decisão</span><strong>Pesquisa e critérios operacionais</strong></div><div><span>Proteção</span><strong>Autenticação contra fraudes</strong></div><div><span>Operação</span><strong>Viagens, eventos e integrações</strong></div></div></section><section class=\"enterprise-rail\" aria-label=\"Contextos atendidos\"><div class=\"container enterprise-rail-inner\"><span>Transportadoras</span> <span>Embarcadores</span> <span>Gerenciadoras de risco</span> <span>Seguradoras</span> <span>Ecossistemas de software</span></div></section><section class=\"section control-statement\"><div class=\"container control-statement-grid\"><div><span class=\"eyebrow\">Visão integrada de risco</span><h2>Informação isolada não protege uma operação complexa.</h2></div><div class=\"control-statement-copy\"><p>O risco surge entre sistemas, pessoas e decisões. A Viagate organiza esses pontos em uma jornada operacional com contexto, evidências e continuidade.</p><a class=\"text-link text-link-large\" href=\"/sobre\">Conheça a visão Viagate <span aria-hidden=\"true\">→</span></a></div></div><div class=\"container risk-chain\" aria-label=\"Cadeia de controle operacional\"><div><span class=\"risk-index\">01</span><div class=\"risk-icon\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.Icon("scan-face").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div><h3>Confirmar</h3><p>Identidade e presença antes de autorizar a jornada.</p></div><div><span class=\"risk-index\">02</span><div class=\"risk-icon\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.Icon("user-check").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</div><h3>Analisar</h3><p>Dados e critérios reunidos com origem e finalidade.</p></div><div><span class=\"risk-index\">03</span><div class=\"risk-icon\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.Icon("shield-check").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div><h3>Proteger</h3><p>Autenticação adicional nos momentos mais sensíveis.</p></div><div><span class=\"risk-index\">04</span><div class=\"risk-icon\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.Icon("route").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</div><h3>Acompanhar</h3><p>Eventos e viagem conectados à decisão inicial.</p></div></div></section><section class=\"flagship-section\"><div class=\"flagship-noise\" aria-hidden=\"true\"></div><div class=\"container flagship-grid\"><div class=\"flagship-copy\"><span class=\"product-overline\"><span></span> Plataforma Cargo / Cargo Score</span><h2>Uma camada de inteligência entre o cadastro e a decisão.</h2><p>O Cargo Score transforma validações dispersas em uma jornada digital com biometria, consentimento, regras configuráveis e histórico operacional.</p><ul class=\"flagship-list\"><li><span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.Icon("scan-face").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</span><div><strong>Presença e identidade</strong><small>Biometria facial e prova de vida dentro do fluxo.</small></div></li><li><span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.Icon("sliders").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</span><div><strong>Política operacional</strong><small>Critérios compatíveis com cada perfil de operação.</small></div></li><li><span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.Icon("history").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "</span><div><strong>Contexto preservado</strong><small>Status, reanálise e histórico para revisão.</small></div></li></ul><a class=\"button\" href=\"/solucoes/pesquisa-cadastral-de-motoristas\">Conhecer o Cargo Score</a></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.BiometricCore().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "</div></section><section class=\"section ecosystem-section\"><div class=\"container ecosystem-heading\"><div><span class=\"eyebrow\">Ecossistema modular</span><h2>Quatro frentes. Uma arquitetura operacional.</h2></div><p>Comece pelo ponto de maior risco e conecte novas capacidades sem fragmentar o processo.</p></div><div class=\"container power-grid\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for index, solution := range solutions {
				templ_7745c5c3_Err = components.PowerSolutionCard(solution, index+1).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "</div><div class=\"container ecosystem-action\"><a class=\"button button-outline\" href=\"/solucoes\">Ver todo o ecossistema</a></div></section><section class=\"section enterprise-control\"><div class=\"container enterprise-control-grid\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.ImagePlaceholder("Painel real da Plataforma Cargo mostrando validação cadastral, alertas, fontes consultadas, mapa da operação e trilha de auditoria.", "1920 x 1280 px - proporção 3:2", "enterprise-control-image").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "<div class=\"enterprise-control-copy\"><span class=\"eyebrow\">Visibilidade para equipes exigentes</span><h2>O que aconteceu, por que aconteceu e qual é o próximo movimento.</h2><p>Interfaces operacionais precisam reduzir dúvida, não apenas exibir dados. Cada etapa é organizada para preservar contexto e apoiar a atuação humana.</p><div class=\"control-points\"><div><span>01</span><p><strong>Origem identificada</strong>Informações vinculadas às fontes aplicáveis.</p></div><div><span>02</span><p><strong>Critério visível</strong>Regras e status compreensíveis para a equipe.</p></div><div><span>03</span><p><strong>Trilha preservada</strong>Eventos essenciais registrados para auditoria.</p></div></div></div></div></section><section class=\"integration-section\"><div class=\"container integration-grid\"><div class=\"integration-copy\"><span class=\"product-overline\"><span></span> Integrações via API</span><h2>A inteligência Viagate dentro da arquitetura da sua empresa.</h2><p>Conecte biometria, cadastros e operações aos sistemas já utilizados pela equipe, com uma abordagem modular e orientada ao processo.</p><div class=\"integration-tags\"><span>REST</span><span>JSON</span><span>Webhooks</span><span>White label</span></div><a class=\"button button-light\" href=\"/integracoes/api\">Explorar integrações</a></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.ApiConsole().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "</div></section><section class=\"section knowledge-section\"><div class=\"container knowledge-heading\"><div><span class=\"eyebrow\">Inteligência aplicada</span><h2>Conteúdo para decisões que não aceitam improviso.</h2></div><a class=\"text-link text-link-large\" href=\"/blog\">Acessar central de conteúdo <span aria-hidden=\"true\">→</span></a></div><div class=\"container article-grid\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for _, article := range articles {
				templ_7745c5c3_Err = components.ArticleCard(article).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "</div></section>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.CallToAction("Sua operação já produz dados. Falta transformá-los em controle.", "Converse com a Viagate para mapear riscos, integrações e a jornada ideal para o seu cenário.").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = components.Layout(meta).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
