// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/viagate/site/internal/site"
	"github.com/viagate/site/web/components"
)

func Solutions(meta site.PageMeta, solutions []site.Solution) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"solutions-command-hero\"><div class=\"command-grid\" aria-hidden=\"true\"></div><div class=\"command-glow command-glow-left\" aria-hidden=\"true\"></div><div class=\"container solutions-command-copy\"><div class=\"authority-line\"><span class=\"authority-dot\"></span> Ecossistema Viagate</div><h1>Uma arquitetura para controlar os pontos críticos da operação.</h1><p>Valide identidades, organize cadastros, proteja negociações, acompanhe viagens e conecte dados ao ambiente tecnológico da empresa.</p></div><div class=\"container solutions-principles\"><div><small>01 / MODULAR</small><strong>Comece pelo risco prioritário</strong></div><div><small>02 / CONECTADO</small><strong>Preserve o contexto entre etapas</strong></div><div><small>03 / RASTREÁVEL</small><strong>Mantenha evidências operacionais</strong></div></div></section><section class=\"section solutions-catalog\"><div class=\"container ecosystem-heading\"><div><span class=\"eyebrow\">Capacidades</span><h2>Escolha o ponto de entrada. Conecte o restante quando fizer sentido.</h2></div><p>Cada solução atende a um problema específico e pode compor uma jornada maior dentro do ecossistema Viagate.</p></div><div class=\"container power-grid power-grid-catalog\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for index, solution := range solutions {
				templ_7745c5c3_Err = components.PowerSolutionCard(solution, index+1).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div></section><section class=\"section solutions-architecture\"><div class=\"container solutions-architecture-grid\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.ImagePlaceholder("Arquitetura modular mostrando produtos Viagate conectados ao TMS, ERP, gerenciadoras de risco e sistemas do cliente.", "1800 x 1200 px - proporção 3:2", "solutions-architecture-image").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<div><span class=\"eyebrow\">Integração sem ruptura</span><h2>Use a plataforma ou leve os recursos ao seu sistema.</h2><p>As soluções podem compor uma jornada dentro da Plataforma Cargo, ser integradas por API ou disponibilizadas em experiência white label, conforme o projeto.</p><ul class=\"architecture-list\"><li><span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.Icon("workflow").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</span><div><strong>APIs modulares</strong><small>Capacidades incorporadas ao fluxo atual.</small></div></li><li><span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.Icon("palette").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</span><div><strong>Experiência white label</strong><small>Jornadas alinhadas à marca contratante.</small></div></li><li><span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.Icon("database").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</span><div><strong>Plataforma Cargo</strong><small>Ambiente operacional centralizado.</small></div></li></ul><a class=\"button button-outline\" href=\"/integracoes/api\">Conheça as integrações</a></div></div></section>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.CallToAction("Qual ponto da operação precisa de mais controle?", "Apresente o processo atual e receba uma proposta alinhada à realidade da sua empresa.").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = components.Layout(meta).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
